### PR TITLE
Messages shaked

### PR DESCRIPTION
**Pull request by shakedhagag**
# PR Description

Finished messages, messageTags, messageBoards model classes
mad migartions for each.

### CODE REVIEW

**Comment by DanWaldman** [comment]
Fantastic

**Review by DanielItkes — APPROVED** [review]

**Review by DanWaldman — APPROVED** [review]
amazing

**Review by razashtar93 — APPROVED** [review]

**Comment by razashtar93** [comment]
- AcadeMeData/migrations/0002_User_test_data.py
- AcadeMeData/migrations/0006_university_test_data.py
- AcadeMeData/migrations/0008_Professor_test_data.py
All those file was deleted in this PR - if merging this will delete those file in main then we need to add them back.

**Comment by DanWaldman** [comment]
Resolved #41 #44 #46

**Review by Yarboa — COMMENTED** [review]
What is the difference from #65

**Comment by shakedhagag** [comment]
> What is the difference from #65

I seem to have used git add * on both PR's
my bad

**Pull request closed without merging**
