### PR TITLE
[Backend + Frontend] Courses - Message Boards Inheritance 

### LINKED ISSUE #130: Connect each course to its own MsgBoard
## Course-MsgBoard Inheritance

Our model supports the msgboard inheritance, more specifically we can look at our app flow like so - 
Uni ---> Degree ---> Courses ---> Course ---> MsgBoard

Basically everything exists, just waiting for the last pr to be merged before starting to work on this issue.

### PR DESCRIPTION
**Pull request by shakedhagag**
## Connecting between Courses and Message Boards

In this PR we are adding a unique message board to each course
It is basically connecting all the last PR's, so there is not much changed.

See you in 08:45 ! 😀 

Closes #130

### CODE REVIEW

**Review by razashtar93 — APPROVED** [review]
LGTM

**Review by DanWaldman — APPROVED** [review]
LGTM

**Review by DanielItkes — APPROVED** [review]

**Review by Yarboa — COMMENTED** [review]
I do not see any tests here :)

**Review by Yarboa — APPROVED** [review]
Ignore my last comment, sorry
LGTM

**Pull request merged**
