### PR TITLE
Created SuperUser and added relevant code to admin.py

### PR DESCRIPTION
**Pull request by DeanCivlin**

### CODE REVIEW

**Comment by DanWaldman** [comment]
Amazing

**Review by DanielItkes — APPROVED** [review]
LGTM

**Review by razashtar93 — APPROVED** [review]
LGTM

**Review by DanWaldman — APPROVED** [review]

**Review by shakedhagag — COMMENTED** [review]
Reviewed. made together

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
