### PR TITLE
Added Pytest and all related files

### PR DESCRIPTION
**Pull request by DanielItkes**
Added pytest and all related files. 
This will in theory fix our problems with the tests files, we will now be able to modify them to work.
#55

### CODE REVIEW

**Comment by Yarboa** [comment]
Thanks for taking it
Please fix the tests which
Consider using the following in tests.

@pytest.mark.django_db

remove @pytest, use different asserts, 
once User added or deleted, use the following
users_list = User.objects.all()
you can play and understand it from vagrant run the follwoing command  
pipenv run python manage.py shell
from AcadeMeData.models import User
users_list= User.objects.all()
You can iterate it 
users_list[0].user.username

**Comment by DanielItkes** [comment]
Please approve this PR so we can use the pytest for all our PRs.
The only reason there is a test failed with this PR is because Users that was already merged gives us an error.

**Comment by Yarboa** [comment]
> Please approve this PR so we can use the pytest for all our PRs. The only reason there is a test failed with this PR is because Users that was already merged gives us an error.

Correct, the fix of this test should be in this PR, lets work on it

**Comment by DanielItkes** [comment]
#59

**Pull request closed without merging**
