### PR TITLE
Split AcadeMeData to apps

### PR DESCRIPTION
**Pull request by DanWaldman**
split all files from AcadeMeData to separate apps:
- user - containing User
- professor - containing Professor
- studies - containing Course, Degree, University
- forums - containing Messages, MessageBoards, MessageTags

Added:
- code for user - model, tests and migrations
- code for studies - model, tests and migrations (only for university - still missing course and degree)
- code for professor - model, tests and migrations
- all tests are now in correct format of fixtures and methods

***most code in this PR is not new - this PR is meant for rearranging the project for it to be more clean and separated***
#68

### CODE REVIEW

**Comment by DanielItkes** [comment]
LGTM

**Review by DanielItkes — APPROVED** [review]

**Review by Yarboa — COMMENTED** [review]
Do you think that your tables are so complex, that each table deserve an app? 
I would consider splitting for two apps as a minimum.

There is another option to split models as per this guideline 
https://docs.djangoproject.com/en/3.2/topics/db/models/

You will have separation in tables and tests from here.
I wonder what others think

**Comment by DanWaldman** [comment]
@Yarboa I wonder, what is wrong with 4 tables? Why is this a problem?

**Comment by Yarboa** [comment]
> @Yarboa I wonder, what is wrong with 4 apps? Why is this a problem? Not every table gets an app. User gets an app Proffesor gets an app Messages, messagetags, and messageboards gets an app And university, course, and degree gets an app. I myself think this is a great separation.

Consider this guidelines for the App
https://docs.djangoproject.com/en/3.2/ref/applications/

Please Think why you need an app for professor? what are the views and Models Professor has?

**Review by bregman-arie — CHANGES_REQUESTED** [review]
It doesn't make sense to have an app for every model.
Also, the PR is way too big. Expect reviewers to review 41 changes is not reasonable.

**Comment by Yarboa** [comment]
> It doesn't make sense to have an app for every model. Also, the PR is way too big. Expect reviewers to review 41 changes is not reasonable.

@DanWaldman consider this change
I suggested and tested for @shakedhagag 
https://pastebin.com/ZS5CP5iJ

**Comment by Omeramsc** [comment]
> @Yarboa I wonder, what is wrong with 4 apps? Why is this a problem? Not every table gets an app. User gets an app Proffesor gets an app Messages, messagetags, and messageboards gets an app And university, course, and degree gets an app. I myself think this is a great separation.

Maybe now 4 apps don't seem like much, but what will happen when AcadeMe will grow? will you keep adding apps, or refactor everything? better do that now than have a technical debt to deal with later. 
I'd also suggest dividing the apps one by one, as the PR is humongous and hard to review; you should also rebase it to solve conflicts, where the complexity of it will show.

**Pull request closed without merging**
