### PR TITLE
Remove the user module 'type' property

### LINKED ISSUE #77: Remove the user module 'type' property
After a team discussion - it was agreed to remove 'type' property from user.
This was decided after we came to the agreement that a user may be a student for a certain course, and an expert for another, and therefore a field defining if a user is an expert or student would be wrong.

### PR DESCRIPTION
**Pull request by DanWaldman**
in this PR we:
- resolved #77 
- changed dependencies in test data files - to point on previous test data file (as requested).
- Removed field "type" from User as we decided it is no longer needed.
- fixed user_test_data because of the change above.
- made new migrations because of the change above .

### CODE REVIEW

**Review by Omeramsc — CHANGES_REQUESTED** [review]
Good job! 
1. Please link an issue to the PR. 
2. way better descriptions and titles than before. I would however improve the title. think about something along the lines of "Remove the user module 'type' property", which gives more context about what has changed, and where. since migrations and tests are almost always affected by such changes, you shouldn't mention them in the title (it is however ok to mention them in the description)
3. you should have a separated migration file for the alterations made. [never edit an existing migration file](https://stackoverflow.com/questions/58926154/any-dangers-of-modifying-an-existing-migration-file#:~:text=In%20general%2C%20editing%20existing%20migrations,performs%20the%20changes%20you%20require.).  You can read more about Django migrations [here](https://docs.djangoproject.com/en/3.2/topics/migrations/)

**Comment by DanWaldman** [comment]
@Omeramsc linked an issue about PR and changed the name. about 3, if this was already done is there something to do? should I  redo this?

**Comment by Omeramsc** [comment]
> @Omeramsc linked an issue about PR and changed the name. about 3, if this was already done is there something to do? should I redo this?

Yes, you should redo it. return the old migration file, make sure your local DB is reverted, and create a new migration for the alterations

**Comment by DanWaldman** [comment]
> > @Omeramsc linked an issue about PR and changed the name. about 3, if this was already done is there something to do? should I redo this?
> 
> Yes, you should redo it. return the old migration file, make sure your local DB is reverted, and create a new migration for the alterations

I think I misunderstood before. 
When I changed the test data and user model, I first erased the db.sqlite3 file and then made the migrations. That process was correct? @Omeramsc

**Comment by Yarboa** [comment]
> Good job!
> 
> 1. Please link an issue to the PR.
> 2. way better descriptions and titles than before. I would however improve the title. think about something along the lines of "Remove the user module 'type' property", which gives more context about what has changed, and where. since migrations and tests are almost always affected by such changes, you shouldn't mention them in the title (it is however ok to mention them in the description)
> 3. you should have a separated migration file for the alterations made. [never edit an existing migration file](https://stackoverflow.com/questions/58926154/any-dangers-of-modifying-an-existing-migration-file#:~:text=In%20general%2C%20editing%20existing%20migrations,performs%20the%20changes%20you%20require.).  You can read more about Django migrations [here](https://docs.djangoproject.com/en/3.2/topics/migrations/)

Thanks @Omeramsc, although it is not a must.
In case of deletion of init file, all data will be generated automatically again,
The fixes are created clean by makemigration,

**Comment by Yarboa** [comment]
> > > @Omeramsc linked an issue about PR and changed the name. about 3, if this was already done is there something to do? should I redo this?
> > 
> > 
> > Yes, you should redo it. return the old migration file, make sure your local DB is reverted, and create a new migration for the alterations
> 
> I think I misunderstood before. When I changed the test data and user model, I first erased the db.sqlite3 file and then made the migrations. That process was correct? @Omeramsc

db.sqlite is created on makemigrations without data,
once migrates run the files are populated.

I assume @Omeramsc refers to the 0001_initial, which created in makemigrations operation,
Isnt it?

**Comment by Omeramsc** [comment]
@Yarboa `0001_initial` indeed is the file that should not change. 
I do and should insist of it, as this is a project worked on by multiple people; while Dan can remove and modify his migrations and db, others may encounter issues if the true source of their DB is suddenly changed while their local (or production...) DB uses different configurations

**Comment by DanWaldman** [comment]
> @Yarboa `0001_initial` indeed is the file that should not change. 
> I do and should insist of it, as this is a project worked on by multiple people; while Dan can remove and modify his migrations and db, others may encounter issues if the true source of their DB is suddenly changed while their local (or production...) DB uses different configurations

I understand, but, can't they just remove their db and then rerun migrations? I don't see how initial001.py can't change, for example it used to have the dictionary of 'E' = 'Expert' 
'S' = 'Student'
Which doesn't exist anymore..

**Comment by Yarboa** [comment]
> > @Yarboa `0001_initial` indeed is the file that should not change.
> > I do and should insist of it, as this is a project worked on by multiple people; while Dan can remove and modify his migrations and db, others may encounter issues if the true source of their DB is suddenly changed while their local (or production...) DB uses different configurations
> 
> I understand, but, can't they just remove their db and then rerun migrations? I don't see how initial001.py can't change, for example it used to have the dictionary of 'E' = 'Expert' 'S' = 'Student' Which doesn't exist anymore..



> > @Yarboa `0001_initial` indeed is the file that should not change.
> > I do and should insist of it, as this is a project worked on by multiple people; while Dan can remove and modify his migrations and db, others may encounter issues if the true source of their DB is suddenly changed while their local (or production...) DB uses different configurations
> 
> I understand, but, can't they just remove their db and then rerun migrations? I don't see how initial001.py can't change, for example it used to have the dictionary of 'E' = 'Expert' 'S' = 'Student' Which doesn't exist anymore..

See, @DanWaldman I do not agree here neither, but for me it is not a must,
MHO, Since if the code is rebased in other PRs, than it is not so important 

If @Omeramsc insists, i would tend to do what needed inorder to promote the PR

**Comment by Omeramsc** [comment]
Would you say the same if AcadeMe had 100 users and developers? think about all the websites that you're using, would you accept them deleting all of their databases (including your user) just to change one of their fields? That's not the way things work.
We prefer you'll be doing the right way than the short way. 

Have you read the links I mentioned in my former comments? you should have the answer as for "how" there. there's also a ton of information about it on google.

**Comment by DanWaldman** [comment]
> Would you say the same if AcadeMe had 100 users and developers? think about all the websites that you're using, would you accept them deleting all of their databases (including your user) just to change one of their fields? That's not the way things work.
> We prefer you'll be doing the right way than the short way. 
> 
> Have you read the links I mentioned in my former comments? you should have the answer as for "how" there. there's also a ton of information about it on google.

Understood, I'll work on it later today

**Comment by DanWaldman** [comment]
@Omeramsc In the last commit I returned the 0001_initial to it's old state and reverted db. 
Sadly I looked a lot online and couldn't figure out how to make a different file or how I should go about from there. 
if you have time (maybe tomorrow morning) I'd be happy if you could help me out with this with more specifics, so that we can finally merge this PR. 
thanks.

**Review by Yarboa — APPROVED** [review]

**Review by DanielItkes — APPROVED** [review]

**Review by razashtar93 — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
Please rebase

**Comment by Yarboa** [comment]
Please rebase

**Comment by Omeramsc** [comment]
@DanWaldman You should make sure you have the old migration and the db set up as it was before the change (like you have now if I understood correctly), perform the change in the code (remove the type property) - and run the script that creates the migrations.

**Comment by Yarboa** [comment]
Please rebase

**Comment by DanWaldman** [comment]
Rebased and pushed, reverted 0001_initial to former version, changed the code and made migrations.
@Yarboa @Omeramsc

**Review by bregman-arie — APPROVED** [review]

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
