### PR TITLE
Messages migrations

### LINKED ISSUE #82: Add migration files for Messages classes
## Migration

Add migration files for each of the classes:

0003_messageBoards_test_data
0004_messages_test_data
0005_messageTags_test_data

### PR DESCRIPTION
**Pull request by shakedhagag**
## Messages migrations pull-request

Added migrations for each class:
Messages
MessageBoard
MessageTags

Please review and merge if everything checks
closes #82

### CODE REVIEW

**Review by Yarboa — APPROVED** [review]
Please add team memebrs for review
I do not see reason for splitting, but lets hears others, 

Although the following should be in the same PR, if you introduce new models
model, migration files, extra files created by new migration
LGTM

**Comment by shakedhagag** [comment]
> Please add team memebrs for review I do not see reason for splitting, but lets hears others,
> 
> Although the following should be in the same PR, if you introduce new models model, migration files, extra files created by new migration LGTM

No reason for splitting the migration files? 
It is not neccessary but we planned it long ago and it doesnt hurt. 
Got your comment about the same pr, would do it in the future pr's when adding classes and migration files.
Asked for more team members to review.
Thanks.

**Review by DanielItkes — APPROVED** [review]
Nice work!

**Review by bregman-arie — APPROVED** [review]
Looks good to me :)

**Review by Yarboa — APPROVED** [review]
LGTM

**Review by razashtar93 — APPROVED** [review]
LGTM

**Pull request merged**
